# -*- coding: utf-8 -*-
"""Application metadata used by runtime UI surfaces."""

APP_NAME = "Dark Calendar"
APP_VERSION = "3.6.1"
APP_RELEASE_CHANNEL = "Stable"
APP_RELEASE_DATE = "2026-07-18"
APP_VERSION_LABEL = f"v{APP_VERSION}"
APP_VERSION_DISPLAY = f"{APP_VERSION_LABEL} · {APP_RELEASE_CHANNEL}"
APP_VERSION_DETAIL = f"{APP_VERSION_DISPLAY} · {APP_RELEASE_DATE}"
APP_AUTHOR = "김효진"
APP_EMAIL = "aplus.mylife@gmail.com"
APP_LICENSE_NAME = "GNU General Public License v3.0"
APP_LICENSE_SPDX = "GPL-3.0-only"
APP_SOURCE_URL = "https://github.com/Namer-kimhyojin/DARK-CALENDAR"
APP_RELEASE_SOURCE_URL = f"{APP_SOURCE_URL}/releases/tag/v{APP_VERSION}"
APP_LICENSE_URL = f"{APP_SOURCE_URL}/blob/v{APP_VERSION}/LICENSE"
